---
- name: Build and Push {{ source_repo }}:{{ source_branch }}
  hosts: localhost
  vars:
    source_repo: ansible/awx
    source_branch: devel
    # build image
    build_image_push: true
    build_image_registry: "ttl.sh"
    build_image_repo: ""
    build_image_tag: ""
    build_image: "{{ build_image_registry }}/{{ build_image_repo }}:{{ build_image_tag }}"
    # deploy to kubernetes
    deploy: false
    deploy_namespace: awx
#
  tasks:
#
  - name: Clone {{ source_repo }}:{{ source_branch }} from github.com
    ansible.builtin.git:
      repo: https://github.com/{{ source_repo }}.git
      dest: src/{{ source_repo }}
      single_branch: yes
      version: "{{ source_branch }}"
      force: true

  - name: Set build_image repo and tag when using ttl.sh
    ansible.builtin.set_fact:
      build_image_repo: "{{ ansible_date_time.iso8601_micro | to_uuid }}"
      build_image_tag: 1h
    when: build_image_registry == "ttl.sh"

  - name: Set AWX Facts
    ansible.builtin.set_fact:
      build_playbook: src/{{ source_repo }}/tools/ansible/build.yml 

  # anticipate playbook
  - name: Build and Push AWX to {{ build_image }}
    ansible.builtin.shell:
      cmd: ansible-playbook --connection=local 127.0.0.1 -v -e registry={{ build_image_registry }} -e awx_image={{ build_image_repo }} -e awx_image_tag={{ build_image_tag }} -e push={{ build_image_push }} {{ build_playbook }}