---
- name: Build Operator from Source and Deploy to Kubernetes
  hosts: localhost
  vars:
    # clone source
    source_repo: ""
    source_branch: ""
    # build image
    build_image_registry: ""
    build_image_repo: ""
    build_image_tag: ""
    build_image_push: false    
    build_image: "{{ build_image_registry }}/{{ build_image_repo }}:{{ build_image_tag }}"
    # deploy to kubernetes
    deploy: false
    deploy_namespace: ""
#
  tasks:  
#
  - name: Clone {{ source_repo }}:{{ source_branch }} from github.com
    ansible.builtin.git:
      repo: git@github.com:{{ source_repo }}.git
      dest: src/{{ source_repo }}
      single_branch: yes
      version: "{{ source_branch }}"
      force: true

  - name: Build and optionally push image {{ build_image }}
    community.docker.docker_image:
      build:
        path: src/{{ source_repo }}
      name: "{{ build_image }}"
      push: "{{ build_image_push }}"
      source: build

  - name: Make deploy
    community.general.make:
      chdir: src/{{ source_repo }}
      target: deploy
      params:
        NAMESPACE: "{{ deploy_namespace }}" 
        IMG: "{{ build_image }}"
    when: deploy | bool