---
- name: Build and Push AWX
  hosts: localhost
  vars:
    # clone source
    clone_git: github.com
    clone_repo: ansible/awx
    clone_branch: devel
    # build image
    build_image_push: false
    build_image_registry: "ttl.sh"
    build_image_repo: ""
    build_image_tag: ""
    build_image: "{{ build_image_registry }}/{{ build_image_repo }}:{{ build_image_tag }}"
    # deploy to kubernetes
    deploy: false
    deploy_namespace: awx
    # build vars
    awx_image: "{{ build_image_repo }}"
    awx_image_tag: "{{ build_image_tag }}"
    build_dev: false
    kube_dev: false
    headless: no
    dockerfile_dest: src/{{ clone_repo }}
    dockerfile_name: Dockerfile
    template_dest: _build
    receptor_image: quay.io/ansible/receptor:devel
    image_architecture: '{{ { "x86_64": "amd64", "aarch64": "arm64", "armv7": "arm", "arm64": "arm64", "ppc64le": "ppc64le" }[ansible_facts.architecture] }}'  
#
  tasks:
#
  - name: Get Podman Info
    ansible.builtin.set_fact:
      podman_info: "{{ lookup('ansible.builtin.pipe', 'podman info -f json') }}"

  - name: Clone {{ clone_repo }}:{{ clone_branch }} from {{ clone_git }}
    ansible.builtin.git:
      repo: https://{{ clone_git }}/{{ clone_repo | lower }}.git
      dest: "{{ clone_dest | default('src/' + clone_repo + '/' + clone_branch) }}"   
      accept_hostkey: true
      single_branch: yes
      version: "{{ clone_branch }}"
      force: true

  - name: Set build_image repo and tag when using ttl.sh
    ansible.builtin.set_fact:
      build_image_repo: "{{ ansible_date_time.iso8601_micro | to_uuid }}"
      build_image_tag: 1h
    when: build_image_registry == "ttl.sh"

  - name: Get version from SCM if not explicitly provided
    community.general.make:
      chdir: src/{{ clone_repo }}/{{ clone_branch }}
      target: print-VERSION
    register: scm_version
    failed_when: not scm_version.stdout
    when: awx_version is not defined    

  - name: Set awx_version
    ansible.builtin.set_fact:
      awx_version: "{{ scm_version.stdout | split('+') | first  }}"
    when: awx_version is not defined

  - name: Create _build directory
    ansible.builtin.file:
      path: src/{{ clone_repo }}/{{ clone_branch }}/_build
      state: directory

  - name: Render supervisor configs
    ansible.builtin.template:
      src: src/{{ clone_repo }}/{{ clone_branch }}/tools/ansible/roles/dockerfile/templates/{{ item }}.conf.j2
      dest: src/{{ clone_repo }}/{{ clone_branch }}/_build/{{ item }}.conf
    with_items:
      - supervisor_web
      - supervisor_task
      - supervisor_rsyslog

  - name: Render Dockerfile
    ansible.builtin.template:
      src: src/{{ clone_repo }}/{{ clone_branch }}/tools/ansible/roles/dockerfile/templates/Dockerfile.j2
      dest: src/{{ clone_repo }}/{{ clone_branch }}/Dockerfile

  - name: Verify awx-logos directory exists for official install
    ansible.builtin.stat:
      path: src/{{ clone_repo }}/{{ clone_branch }}/awx-logos
    register: logosdir
    failed_when: logosdir.stat.isdir is not defined or not logosdir.stat.isdir
    when: awx_official|default(false)|bool

  - name: Copy logos for inclusion in sdist
    ansible.builtin.copy:
      src: src/{{ clone_repo }}/{{ clone_branch }}/awx-logos/awx/ui/client/assets/
      dest: src/{{ clone_repo }}/{{ clone_branch }}/awx/ui/public/static/media/
    when: awx_official|default(false)|bool

  - name: Build AWX image {{ build_image }} with podman
    containers.podman.podman_image:
      name: "{{ build_image }}"
      path: src/{{ clone_repo }}/{{ clone_branch }}
      push: "{{ build_image_push }}"
      build:
        extra_args: "--build-arg VERSION={{ awx_version }} --build-arg SETUPTOOLS_SCM_PRETEND_VERSION={{ awx_version }} --build-arg HEADLESS={{ headless }}"
    register: podman_build
    until: podman_build is not failed
    retries: 1
    delay: 10