---
- name: Build Image from Source and Deploy to Kubernetes
  hosts: localhost
  vars:
    # clone source
    source_repo: ""
    source_branch: ""
    # build image
    build_image_push: true   
    build_image_registry: quay.io
    build_image_repo: ""
    build_image_tag: "" 
    build_image: "{{ build_image_registry }}/{{ build_image_repo }}:{{ build_image_tag }}"
    # deploy to kubernetes
    deploy: false
    deploy_namespace: ""
#
  tasks:  
#
  - name: Clone from https://github.com:/{{ source_repo }}:{{ source_branch }}
    ansible.builtin.git:
      repo: https://github.com/{{ source_repo }}
      dest: src/
      single_branch: yes
      version: "{{ source_branch }}"
      force: true

  - name: Build and optionally push {{ build_image }}
    community.docker.docker_image:
      build:
        path: src/
      name: "{{ build_image }}"
      tag: v1
      push: "{{ build_image_push }}"
      source: build

  - name: Make deploy to kubernetes cluster
    make:
      chdir: artifacts/src/
      target: deploy
      params:
        NAMESPACE: "{{ deploy_namespace }}" 
        IMG: "{{ build_image }}"
    when: deploy | bool