---
- name: Build AWX Docker Images
  hosts: localhost
  gather_facts: true
  tasks:
    - name: Get version from SCM if not explicitly provided
      shell: |
        make print-VERSION | cut -d + -f -1
      args:
        chdir: artifacts/src/awx
      register: scm_version
      failed_when: not scm_version.stdout
      when: awx_version is not defined

    - name: Set awx_version
      set_fact:
        awx_version: "{{ scm_version.stdout }}"
      when: awx_version is not defined

    - include_role:
        name:  artifacts/src/awx/tools/ansible/roles/dockerfile
    - include_role:
        name:  artifacts/src/awx/tools/ansible/roles/image_build
    - include_role:
        name:  artifacts/src/awx/tools/ansible/roles/image_push
      when: push | default(false) | bool
