---
- name: Build {{ image_name }} Image from Source and Deploy to Kubernetes
  hosts: localhost
  vars:
    image_name: awx
    # clone source
    source_repo: ansible/awx
    source_branch: devel
    # build image
    build_image_registry: quay.io
    build_image_repo: ""
    build_image_tag: ""
    build_image_push: true    
    build_image: "{{ build_image_registry }}/{{ build_image_repo }}/{{ image_name }}:{{ build_image_tag }}"
    build_playbook: ""
    # deploy to kubernetes
    deploy: true
    deploy_namespace: ""
#
  tasks:  
#
  - name: Clone {{ source_repo }}:{{ source_branch }} from github.com
    ansible.builtin.git:
      repo: git@github.com:{{ source_repo }}.git
      dest: "{{ image_name }}"
      single_branch: yes
      version: "{{ source_branch }}"
      force: true

- name: Build and Push AWX Image
  hosts: localhost
  gather_facts: true
  tasks:
    - name: Get version from SCM if not explicitly provided
      shell: |
        make print-VERSION | cut -d + -f -1
      args:
        chdir: awx
      register: scm_version
      failed_when: not scm_version.stdout
      when: awx_version is not defined

    - name: Set awx_version
      set_fact:
        awx_version: "{{ scm_version.stdout }}"
      when: awx_version is not defined

    - include_role:
        name:  awx/tools/ansible/roles/dockerfile
      vars:
        playbook_dir: awx/tools/ansible
    - include_role:
        name:  awx/tools/ansible/roles/image_build
      vars:
        playbook_dir: awx/tools/ansible
    - include_role:
        name:  awx/tools/ansible/roles/image_push
      vars:
        playbook_dir: awx/tools/ansible
      when: push | default(false) | bool
