---
- name: Test podman playbook
  hosts: localhost

#
  tasks:  
#
  - name: Get Podman Info
    ansible.builtin.set_fact:
      podman_info: "{{ lookup('ansible.builtin.pipe', 'podman info -f json') }}"
#    ignore_errors: true

  - name: Build test image with podman
    containers.podman.podman_image:
      name: test
      path: "{{ playbook_dir }}"
      build:
        extra_args: "--isolation=chroot"