---
- name: Test podman playbook
  hosts: localhost

#
  tasks:  
#
  - name: Get Podman Info
    ansible.builtin.set_fact:
      podman_info: "{{ lookup('ansible.builtin.pipe', 'podman info -f json') }}"
#    ignore_errors: true