---
- name: Run a container with podman
  hosts: localhost
  tasks:

  - name: hello-world
    ansible.builtin.shell:
      cmd: podman run hello-world

  - name: list /stage contents
    ansible.builtin.shell:
      cmd: tree -a /stage/

   - name: Run container
     containers.podman.podman_container:
       name: container
       image: hello-world
       state: started