---
- name: Run a container with podman
  hosts: localhost
  vars:
    stage_repo: ""
    stage_branch: ""
  environment:
    STAGEREPO: "{{ stage_repo }}"
    STAGEBRANCH: "{{ stage_branch }}"
  tasks:

  - name: Show env
    debug:
      msg: "{{ lookup('ansible.builtin.pipe', 'env') }}"

  - name: list /stage contents
    ansible.builtin.shell:
      cmd: tree -aL 1 /stage