---
- name: Run a container with podman
  hosts: localhost
  vars:
    stage_repo: ""
    stage_branch: ""
  environment:
    STAGEREPO: "{{ stage_repo }}"
    STAGEBRANCH: "{{ stage_branch }}"
  tasks:

  - name: Show env
    debug:
      msg: "{{ lookup('ansible.builtin.pipe', 'env') }}"

  - name: hello-world
    ansible.builtin.shell:
      cmd: podman run hello-world

  - name: list /stage contents
    ansible.builtin.shell:
      cmd: tree -a /stage/

  # - name: Run container
  #   containers.podman.podman_container:
  #     name: container
  #     image: hello-world
  #     state: started